; ==================================
; PolyCyGot Action Knowledge
; ==================================

(unsafe-action share-otp)
(unsafe-action share-password)
(unsafe-action share-pin)
(unsafe-action share-api-key)
(unsafe-action reveal-secret)

(unsafe-action click-suspicious-link)
(unsafe-action download-unknown-file)
(unsafe-action disable-mfa)

(unsafe-action bypass-authentication)
(unsafe-action steal-credentials)

(safe-action verify-domain)
(safe-action-contact-bank)
(safe-action-report-phishing)
(safe-action-enable-mfa)
(safe-action-change-password)
(safe-action-contact-official-support)